### PR TITLE
Remove mbstring polyfill from required deps

### PR DESCRIPTION
**Pull request by maennchen**
Description in docs how to install it if needed.

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
You can probably remove the myclabs/enum and use php's enum, too!

**Comment by NicolasCARPi** [comment]
Oh I thought you were targeting php8.1 with all the changes recently!

**Comment by maennchen** [comment]
@NicolasCARPi Everything on `next`: yes. On main `8.0` at the moment.

**Comment by maennchen** [comment]
@andrejpavlovic We don’t want to install additional vendors for users that don’t need it.

If you have a system without mbstring, you can just require it yourself.

**Pull request merged**
