### PR TITLE
Require PHP >= 8.0

### LINKED ISSUE #166: 2021-01-01 - Remove PHP 7.2
# Description of the problem

On 1. of January 2021 PHP 7.2 is EOL. Change the requirement in the `composer.json` and remove it from Travis.

* [ ] Require PHP 7.3 in `composer.json`
* [x] Remove `7.2` from CI Workflow

### PR DESCRIPTION
**Pull request by maennchen**
Closes #166

### CODE REVIEW

**Comment by donatj** [comment]
I'm sorry but this is too soon.  Sure 7.4 is security fixes only right now, but did you even look at the stats of your user base? My name is in the README and I can't use this library now.  This writes off over half your users.

image

https://packagist.org/packages/maennchen/zipstream-php/php-stats

**Comment by maennchen** [comment]
(I'm not using PHP or the library anymore myself in years. But since the library is so popular, I wanted to clean up / release. Thanks for the feedback.)

**Comment by systemsolutionweb** [comment]
Dropping old versions is not a breaking change, it is time

**Comment by maennchen** [comment]
I think there’s multiple facets to this:

* The current code works with PHP 7.4.
* I don’t care about <= 7.3 since it’s completely EOL.
* We’re currently not planning to add features that require >= 8.0

So for now, I have reverted the change. I will remove 7.3 the latest it goes EOL.

I think it’s perfectly valid to introduce improvements, which do only support the latest versions. That does not mean that we take things away from people with older versions but only that they can’t have new features that require it.

If we get improvements (for example better type hints since that is now supported), I’m fine with dropping support earlier.

If we do not get improvements that require a newer version, I also see no reason to prevent people from updating.

The requirement for non EOL versions is important in my opinion, since I have no interest in looking at bug reports etc. from people running unsupported software. Raising the requirement to non EOL is a clear statement for that.

Does everyone agree with that statement?

**Comment by NicolasCARPi** [comment]
I agree that if there are no good reason to raise the bar (like for this present release), then it should not be raised.

**Comment by ericdsd** [comment]
Hi 
i see that 2.2.0 is requiring php >= 8.0, and this prevents me from updating some projects that explicitly requires ^2.2 on php 7.4 (which didn't reach EOL).
Would it be possible to reallow php 7.4 ?

**Comment by NicolasCARPi** [comment]
> Would it be possible to reallow php 7.4 ?

Security support stops in 2 months, so it's as good as EOL IMHO. But the current requirement allows 7.4, so I don't see the need for a change here.

**Comment by japerry** [comment]
The idea that all libraries should drop the minimum version the moment a dependency goes EOL is a sure way to cause user frustration and actually keep customers from updating to the latest version of your code.

7.4 LTS is something most distros are supporting until at least 2025. And unlike 7.2->7.3 and 7.3->7.4, this push to 8 is a much bigger lift for users. The bigger the compatibility window you give for customers, the more likely they won't end up in circular dependency hell trying to update your library when say another unrelated dependency isn't PHP8 compatible yet.

So it should be a goal to keep 7.4 support until there is a compelling reason to require 8+. And certainly, you shouldn't up the minimum just for the heck of it. I maintain many of the most used Drupal modules and plan to keep 7.4 support at least until the end of Drupal 9, which is December 2023.

**Comment by maennchen** [comment]
Dropping the requirement will allow to update the code base in a new minor release.

If we see that we have a large problem and see that the user base is large enough, we can allways just backport a patch release after the fact.

**Pull request merged**
