### PR TITLE
Fix compression in addFileFromStream

### PR DESCRIPTION
**Pull request by sagara-**
gzdeflate() creates a single compression stream, so they can't be concatenated together, which causes the original code to fail on data > 1mb. This patch uses deflate_init (available starting from PHP 7) to properly incrementally compress data. This can be tested by compressing something with size > 1024kb, such as a file created via `fallocate -l1025K dummy.bin`.

### CODE REVIEW

**Comment by ctf0** [comment]
@maennchen could u plz merge this and tag a new release ? as atm any streaming ops will give a corrupted zip file.

**Comment by maennchen** [comment]
@ctf0 I'm testing some known edge cases (mostly with Apple's Unarchiver) right now. Will merge it right after if everything works as expected.

**Comment by maennchen** [comment]
Everything good to go! Thank you very much ❤️

**Comment by maennchen** [comment]
Released as `v0.5.1`

**Pull request merged**
