### PR TITLE
Remote stream leftdevel

### PR DESCRIPTION
**Pull request by apinstein**
This change is [Reviewable](https://reviewable.io/reviews/maennchen/zipstream-php/36)

### CODE REVIEW

**Comment by apinstein** [comment]
Review status: 0 of 3 files reviewed at latest revision, 12 unresolved discussions.

---

*[src/ZipStream.php, line 70 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZkxm7GooT58AYRvTk:-KNZkxm89P5_O2vKsgP8:1515928736) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L70)):*
> ```PHP
>  */
> class ZipStream {
> 	const VERSION                         = '0.3.2';
> ```

probably don't touch their version number

---

*[src/ZipStream.php, line 87 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZq69H7VZJf8WZ3gyE:-KNZq69H7VZJf8WZ3gyF:-1112720464) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L87)):*
> ```PHP
> 
> 	// Zip headers. @see https://en.wikipedia.org/wiki/Zip_(file_format)#File_headers
> 	const HEADER_LOCAL_FILE               = 0x04034b50;
> ```

SIGNATURE_LOCAL_FILE_HEADER

---

*[src/ZipStream.php, line 88 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZq89rC8V6p6F4B7zH:-KNZq89rC8V6p6F4B7zI:1780969620) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L88)):*
> ```PHP
> 	// Zip headers. @see https://en.wikipedia.org/wiki/Zip_(file_format)#File_headers
> 	const HEADER_LOCAL_FILE               = 0x04034b50;
> 	const HEADER_DATA_DESCRIPTIOR         = 0x08074b50;
> ```

SIGNATURE_DATA_DESCRIPTOR_HEADER

---

*[src/ZipStream.php, line 89 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZqAx6t4_RldxoqfV1:-KNZqAx6t4_RldxoqfV2:2099502466) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L89)):*
> ```PHP
> 	const HEADER_LOCAL_FILE               = 0x04034b50;
> 	const HEADER_DATA_DESCRIPTIOR         = 0x08074b50;
> 	const HEADER_CENTRAL_DIRECTORY        = 0x02014b50;
> ```

SIGN..

---

*[src/ZipStream.php, line 90 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZqBt1XeJoZpIPdZmZ:-KNZqBt1XeJoZpIPdZm_:660067052) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L90)):*
> ```PHP
> 	const HEADER_DATA_DESCRIPTIOR         = 0x08074b50;
> 	const HEADER_CENTRAL_DIRECTORY        = 0x02014b50;
> 	const HEADER_END_OF_CENTRAL_DIRECTORY = 0x06054b50;
> ```

SIGN...

---

*[src/ZipStream.php, line 271 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZpFHUILRlMZ3dbub5:-KNZpFHUILRlMZ3dbub6:-668313086) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L271)):*
> ```PHP
> 
> 		// send file header
> 		$bytes_len = $this->sendLocalFileHeader($name, $opt, $meth, $crc, $zlen, $len);
> ```

you'll need to update this to include the $zlen in the bytes written...

---

*[src/ZipStream.php, line 367 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZoxjqv75SCM00VIbZ:-KNZoxjqv75SCM00VIb_:33363869) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L367)):*
> ```PHP
> 
> 		// send local file header.
> 		$initial_bytes_len = $this->sendLocalFileHeader($name, $opt, $meth, $crc, $zlen, $len, $genb);
> ```

change var name -- it's just bytes written...

```
$numBytesWritten = 0;
$numBytesWritten += $this->sendXXX();
```

---

*[src/ZipStream.php, line 399 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZorR-PadkJJQrqHGN:-KNZorR-PadkJJQrqHGO:-424527496) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L399)):*
> ```PHP
> 	 * @param Integer  $zlen
> 	 * @param String   $crc
> 	 * @return Integer $ret_len
> ```

doc as "return bytes written to zip stream output"

---

*[src/ZipStream.php, line 458 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZphV7uN_I_fvne4ck:-KNZphV7uN_I_fvne4cl:1084784213) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L458)):*
> ```PHP
> 	 * @param string   $crc
> 	 * @param Integer  $zlen
> 	 * @param Integer  $len
> ```

add `@param` for general bit

---

*[src/ZipStream.php, line 459 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZmBzH3h8AykrTkc8c:-KNZmBzH3h8AykrTkc8d:-1851219088) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L459)):*
> ```PHP
> 	 * @param Integer  $zlen
> 	 * @param Integer  $len
> 	 * @return Integer $bytes_len
> ```

document --- all these funcs now return num bytes written written to zip stream by this function call; useful for downstream functions to coordinate offset tracking

---

*[src/ZipStream.php, line 532 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZodnV_WO8w1RuA8cb:-KNZodnWV24mHeIQji8L:-2015685329) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L532)):*
> ```PHP
> 		$ret       = $this->packFields($fields);
> 		$header    = $ret . $name;
> 		$bytes_len = strlen($header) + $zlen;
> ```

to keep consistent that all "send" functions return bytes written to string, move `$zlen` out to the caller's responsibility.

---

*[src/ZipStream.php, line 593 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZqUbRYaKHV3XCY_n_:-KNZqUbRYaKHV3XCY_na:-2051567759) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L593)):*
> ```PHP
> 
> 		// send file header
> 		$bytes_len = $this->sendLocalFileHeader($name, $opt, $meth, $crc, $zlen, $len);
> ```

needs to manually add $zlen to length for addToCdr

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maennchen/zipstream-php/36)*

**Comment by apinstein** [comment]
Review status: 0 of 3 files reviewed at latest revision, 15 unresolved discussions.

---

*[src/ZipStream.php, line 342 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZsD8F1tRuYTqmBCUk:-KNZsD8F1tRuYTqmBCUl:2099956471) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/src/ZipStream.php#L342)):*
> ```PHP
> 	 * @param Resource $stream - contents of file as a stream resource
> 	 * @param array $opt - Hash of options for file (optional, see "File Options" below).
> 	 *
> ```

add doc NOTE: right now this only sends uncompressed data.

---

*[test/ZipStreamTest.php, line 162 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZtOBtV4RbS9WIkD_Q:-KNZtOBtV4RbS9WIkD_R:231067118) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/test/ZipStreamTest.php#L162)):*
> ```PHP
> 		$streamExample = fopen('php://temp', 'w+');
> 		fwrite($streamExample, "Sample String Data");
> 		fseek($streamExample, SEEK_SET, 0); // rewind to the start, otherwise there will be no content.
> ```

why not just `rewind()`

---

*[test/ZipStreamTest.php, line 168 \[r1\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNZtbcom7QT7PhlIusu:-KNZtbcom7QT7PhlIusv:231067118) ([raw file](https://github.com/maennchen/zipstream-php/blob/7ca0d2cfc51b336cbc471ff9ac068a727138807f/test/ZipStreamTest.php#L168)):*
> ```PHP
> 		$streamExample2 = fopen('php://temp', 'w+');
> 		fwrite($streamExample2, "More Simple Sample Data");
> 		fseek($streamExample2, SEEK_SET, 0); // rewind to the start, otherwise there will be no content.
> ```

why not just `rewind()`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maennchen/zipstream-php/36)*

**Comment by maennchen** [comment]
Could you please only submit your change? We're going to change the code style to PSR2 for the refactoring. For now the old one should stay.

**Comment by leftdevel** [comment]
@maennchen. Done. Check it out. I've just included the min changes to make the feature to work. Let me know how it looks.

**Comment by maennchen** [comment]
I'm sorry @leftdevel, but there's still many changes to reformat the code, could you please remove them?

**Comment by maennchen** [comment]
@leftdevel: Yes I meant the changes about the white space. I didn't know the trick to hide whitespace though, thank you.

I'll try the changes manually in a few fragile clients (like macs unarchiver for example). If it works, I'll merge.

**Comment by maennchen** [comment]
And thank you very much!

**Comment by apinstein** [comment]
Review status: 0 of 2 files reviewed at latest revision, 16 unresolved discussions.

---

*[src/ZipStream.php, line 347 \[r2\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNe6YpPnv3cDnJ4zpYn:-KNe6YpPnv3cDnJ4zpYo:-1583856993) ([raw file](https://github.com/maennchen/zipstream-php/blob/464901464ab4331e02df977d5f780e636df20e81/src/ZipStream.php#L347)):*
> ```PHP
> 		while (!feof($stream)) {
> 			// Read and send.
> 			$data = fread($stream, $block_size);
> ```

you need to check for `false` here...  what to do on error, I'm not sure...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maennchen/zipstream-php/36)*

**Comment by leftdevel** [comment]
Note I've added some error handling. Happy to discuss what's it about if it's happen to be confusing.

**Comment by apinstein** [comment]
Review status: 0 of 3 files reviewed at latest revision, 17 unresolved discussions.

---

*[src/ZipStream.php, line 379 \[r3\]](https://reviewable.io:443/reviews/maennchen/zipstream-php/36#-KNeWJB0-yMX8AZyz5-h:-KNeWJB0-yMX8AZyz5-i:-1627429137) ([raw file](https://github.com/maennchen/zipstream-php/blob/cf5eb48715f8dea35deaea2a278a6d27d9de35cb/src/ZipStream.php#L379)):*
> ```PHP
> 
> 		// If there was a read error, we still want the cdr to be appended, this way we ensure
> 		// the zip file can be opened if the exception thrown below is handled by the invoker.
> ```

actually I think the ZIP file will still be openable here; you in fact still provide a "valid" CRC for the truncated data (not sure if that's correct)....

Not clear to me what the expectations of how ZipStream behaves in error cases should be.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/maennchen/zipstream-php/36)*

**Comment by tillkruss** [comment]
This broke thing for me. Using 0.3.1 everything works fine, when using v0.4.1 all files have 0 bytes.

**Comment by leftdevel** [comment]
@tillkruss. Does it looks like it's downloading at a normal pace or it downloads everything instantly?
The only issue that I'm aware of is that the stream is non-recoverable, in other words, if the network is unstable a any point the stream will break and the download will halt leaving you with a partial download.

Just for the record, this PR was to allow sending files that are too big that can't be loaded in the server's allocated memory.
If you think you can load your zip file in memory, then I think you can use the previous existing method and see if that one works for you.

**Comment by tillkruss** [comment]
This code works with 0.3.1, but not with 0.4.1:

```php
$zip = new ZipStream('foobar.zip');

foreach ($photos as $photo) {
    $fp = tmpfile();
    $ch = curl_init($photo->url);
    curl_setopt($ch, CURLOPT_TIMEOUT, 120);
    curl_setopt($ch, CURLOPT_FILE, $fp);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_exec($ch);
    curl_close($ch);

    $zip->addFileFromStream($photo->filename, $fp);

    fclose($fp);
}

$zip->finish();
```

**Comment by leftdevel** [comment]
@tillkruss:
I'd bet that the issue is because you need to `rewind` the tmpfile after curl has written to it.
before `$zip->adFileFromStream` put `rewind($fp)`;

The reason it worked before and not with the newer version is because the old method used to do the rewind internally.

The reason the new version doesn't rewind it's because you can't rewind and remote stream. If you do a fopen() on a remote url and try to rewind on the returned handle it will fail.

At this point I don't remember all the details of my PR. And I have the impression I had left the old implementation alone and created a new method. I'll double check later what happened.

In the meanwhile please try the above snippet ^ and let me know how it goes.

**Comment by tillkruss** [comment]
@leftdevel: Thanks a lot, that's working perfectly.

**Pull request merged**
