### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by danielforer**
Described use of ZipStream in a Symfony controller action  method using StreamedResponse.

### CODE REVIEW

**Comment by maennchen** [comment]
I'd propose to create a doc folder containing a Symfony.md file. The README should have a link to it.

**Comment by danielforer** [comment]
@maennchen no worries. I'll make a Symfony.md and link to it in README.md. All good

**Comment by danielforer** [comment]
@maennchen done. Doc folder containing Symfony.md and link in README.md

**Comment by maennchen** [comment]
Thanks!

**Pull request merged**
